name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  ci-cd:
    name: CI/CD
    permissions:
      contents: read
      packages: read
      deployments: write
    uses: significa/actions/.github/workflows/vercel-app.yaml@main
    with:
      npm_scope: '@significa'
      install_registry_url: 'https://npm.pkg.github.com/'
      # FIXME: We cannot run `npm run validate` because `svelte-check` requires runtime env vars to be set
      lint_command: 'npm run lint'
      staging_domain: ${{ vars.STAGING_DOMAIN }}
      production_domain: ${{ vars.PRODUCTION_DOMAIN }}
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
